export const FETCH_COURSES = '@home/FETCH_COURSES'
export const FETCH_COURSES_SUCCESS = '@home/FETCH_COURSES_SUCCESS'
export const FETCH_COURSES_FAILURE = '@home/FETCH_COURSES_FAILURE'

export const COURSES_ENDPOINT = '/courses'